# Dockerfile.api
FROM node:20-alpine

WORKDIR /app

RUN mkdir -p uploads 

# Install pnpm
RUN npm install -g pnpm

COPY ./api/pnpm-lock.yaml ./api/package*.json ./
RUN pnpm install --frozen-lockfile

COPY ./api .
RUN pnpm run build

CMD ["pnpm", "start"]